import { BlogPost } from "./types";

export const projects = [
  {
    name: "Image Format",
    format: "img",
    img: "img/projects/project-1.jpg",
    project: "WEBSITE",
    client: "ENVATO",
    duration: "3 MONTHS",
    technologies: "HTML, JAVASCRIPT",
    budget: "1550 USD",
  },
  {
    name: "Youtube Format",
    format: "youtube",
    img: "img/projects/project-2.jpg",
    project: "WEBSITE",
    client: "ENVATO",
    duration: "3 MONTHS",
    technologies: "HTML, JAVASCRIPT",
    budget: "1550 USD",
  },
  {
    name: "Slider Format",
    format: "slider",
    img: "img/projects/project-3.jpg",
    project: "WEBSITE",
    client: "ENVATO",
    duration: "3 MONTHS",
    technologies: "HTML, JAVASCRIPT",
    budget: "1550 USD",
  },
  {
    name: "Video Format",
    format: "video",
    img: "img/projects/project-4.jpg",
    project: "WEBSITE",
    client: "ENVATO",
    duration: "3 MONTHS",
    technologies: "HTML, JAVASCRIPT",
    budget: "1550 USD",
  },
  {
    name: "Image Format",
    format: "img",
    img: "img/projects/project-5.jpg",
    project: "WEBSITE",
    client: "ENVATO",
    duration: "3 MONTHS",
    technologies: "HTML, JAVASCRIPT",
    budget: "1550 USD",
  },
  {
    name: "Image Format",
    format: "img",
    img: "img/projects/project-6.jpg",
    project: "WEBSITE",
    client: "ENVATO",
    duration: "3 MONTHS",
    technologies: "HTML, JAVASCRIPT",
    budget: "1550 USD",
  },
  {
    name: "Image Format",
    format: "img",
    img: "img/projects/project-7.jpg",
    project: "WEBSITE",
    client: "ENVATO",
    duration: "3 MONTHS",
    technologies: "HTML, JAVASCRIPT",
    budget: "1550 USD",
  },
  {
    name: "Image Format",
    format: "img",
    img: "img/projects/project-8.jpg",
    project: "WEBSITE",
    client: "ENVATO",
    duration: "3 MONTHS",
    technologies: "HTML, JAVASCRIPT",
    budget: "1550 USD",
  },
  {
    name: "Image Format",
    format: "img",
    img: "img/projects/project-9.jpg",
    project: "WEBSITE",
    client: "ENVATO",
    duration: "3 MONTHS",
    technologies: "HTML, JAVASCRIPT",
    budget: "1550 USD",
  },
];

export const blogPosts: BlogPost[] = [
  {
    title: "create a wordpress theme from scratch",
    img: "img/blog/blog-post-1.jpg",
    tag: "Branding",
    date: { day: "23", month: "jun" },
    des: [
      "Oki is a leading web design agency with an award-winning design team that creates innovative, effective websites that capture your brand, improve your conversion rates, and maximize your revenue to help grow your business and achieve your goals.",
      "In today's digital world, your website is the first interaction consumers have with your business. That's why almost 95 percent of a user's first impression relates to web design. It's also why web design services can have an immense impact on your company's bottom line.",
      "That's why more companies are not only reevaluating their website's design but also partnering with Kura, the web design agency that's driven more than $2.4 billion in revenue for its clients. With over 50 web design awards under our belt, we're confident we can design a custom website that drives sales for your unique business.",
    ],
  },
  {
    title: "Effective Marketing Strategy tips",
    img: "img/blog/blog-post-2.jpg",
    tag: "Design",
    date: { day: "23", month: "jun" },
    des: [
      "Oki is a leading web design agency with an award-winning design team that creates innovative, effective websites that capture your brand, improve your conversion rates, and maximize your revenue to help grow your business and achieve your goals.",
      "In today's digital world, your website is the first interaction consumers have with your business. That's why almost 95 percent of a user's first impression relates to web design. It's also why web design services can have an immense impact on your company's bottom line.",
      "That's why more companies are not only reevaluating their website's design but also partnering with Kura, the web design agency that's driven more than $2.4 billion in revenue for its clients. With over 50 web design awards under our belt, we're confident we can design a custom website that drives sales for your unique business.",
    ],
  },
  {
    title: "free psd and sketch ressouces",
    img: "img/blog/blog-post-3.jpg",
    tag: "Media",
    date: { day: "23", month: "jun" },
    des: [
      "Oki is a leading web design agency with an award-winning design team that creates innovative, effective websites that capture your brand, improve your conversion rates, and maximize your revenue to help grow your business and achieve your goals.",
      "In today's digital world, your website is the first interaction consumers have with your business. That's why almost 95 percent of a user's first impression relates to web design. It's also why web design services can have an immense impact on your company's bottom line.",
      "That's why more companies are not only reevaluating their website's design but also partnering with Kura, the web design agency that's driven more than $2.4 billion in revenue for its clients. With over 50 web design awards under our belt, we're confident we can design a custom website that drives sales for your unique business.",
    ],
  },
  {
    title: "How to become a successful freelancer",
    img: "img/blog/blog-post-4.jpg",
    tag: "Technology",
    date: { day: "23", month: "jun" },
    des: [
      "Oki is a leading web design agency with an award-winning design team that creates innovative, effective websites that capture your brand, improve your conversion rates, and maximize your revenue to help grow your business and achieve your goals.",
      "In today's digital world, your website is the first interaction consumers have with your business. That's why almost 95 percent of a user's first impression relates to web design. It's also why web design services can have an immense impact on your company's bottom line.",
      "That's why more companies are not only reevaluating their website's design but also partnering with Kura, the web design agency that's driven more than $2.4 billion in revenue for its clients. With over 50 web design awards under our belt, we're confident we can design a custom website that drives sales for your unique business.",
    ],
  },
];

export const navItems = [
  { id: "home", name: "Home", dkMenuName: "Home", icon: "fa fa-home" },
  { id: "about", name: "About me", dkMenuName: "About", icon: "fa fa-user" },
  {
    id: "work",
    name: "my Portfolio",
    dkMenuName: "Portfolio",
    icon: "fa fa-briefcase",
  },
  {
    id: "contact",
    name: "get in touch",
    dkMenuName: "Contact",
    icon: "fa fa-envelope-open",
  },
  { id: "blog", name: "my Blog", dkMenuName: "Blog", icon: "fa fa-comments" },
];

export const typewriterWords = [
  "Majid Vezvaee",
  "a web developer",
  "an engineer",
  "a freelancer",
];

export const emailRegex = new RegExp(/^[\w-\.]+@([\w-]+\.)+[\w-]{2,4}$/g);

export const INVALID_NAME_KEYS = [
  "1",
  "2",
  "3",
  "4",
  "5",
  "6",
  "7",
  "8",
  "9",
  "0",
  "!",
  "@",
  "#",
  "$",
  "%",
  "^",
  "&",
  "*",
  "(",
  ")",
  "_",
  "+",
  "=",
  "{",
  "}",
  "[",
  "]",
  "|",
  "\\",
  ":",
  ";",
  '"',
  "<",
  ">",
  ",",
  "?",
  "/",
  "~",
  "`",
  ".",
];
